// File: app/changelog/changelogsData.ts
export const changelogsData = [
  {
    date: "23 Mar 2023",
    title: "Update Click/Open Tracking via API",
    desc: "Manage the entire lifecycle of your domains programmatically.",
    image: "/images/blog/blog-5.png",
    authorImg: "https://i.pravatar.cc/150?img=1",
    authorName: "Ahmad Hassan",
  },
  {
    date: "10 Apr 2023",
    title: "Improved Dashboard Performance",
    desc: "Enhanced analytics speed and optimized queries for faster insights.",
    image: "/images/blog/blog-3.png",
    authorImg: "https://i.pravatar.cc/150?img=2",
    authorName: "Bilal Khan",
  },
  {
    date: "18 Apr 2023",
    title: "New Email Templates Library",
    desc: "Access 50+ professionally designed email templates for campaigns.",
    image: "/images/blog/blog-1.png",
    authorImg: "https://i.pravatar.cc/150?img=3",
    authorName: "Sara Ahmed",
  },
  {
    date: "25 Apr 2023",
    title: "Multi-Language Support Added",
    desc: "Platform now supports 20+ languages for global reach.",
    image: "/images/blog/blog-2.png",
    authorImg: "https://i.pravatar.cc/150?img=4",
    authorName: "Usman Ali",
  },
  {
    date: "02 May 2023",
    title: "Advanced Analytics Dashboard",
    desc: "Get deeper insights with our new analytics and reporting tools.",
    image: "/images/blog/blog-4.png",
    authorImg: "https://i.pravatar.cc/150?img=5",
    authorName: "Ayesha Malik",
  },
  {
    date: "09 May 2023",
    title: "Dark Mode Implementation",
    desc: "Reduce eye strain with our sleek new dark mode interface.",
    image: "/images/blog/blog-6.png",
    authorImg: "https://i.pravatar.cc/150?img=6",
    authorName: "Hassan Raza",
  },
  {
    date: "16 May 2023",
    title: "API Rate Limit Increase",
    desc: "Premium users now get 3x higher API rate limits.",
    image: "/images/blog/blog-1.png",
    authorImg: "https://i.pravatar.cc/150?img=7",
    authorName: "Fatima Noor",
  },
  {
    date: "23 May 2023",
    title: "Mobile App Launch",
    desc: "Manage your campaigns on the go with our native mobile apps.",
    image: "/images/blog/blog-5.png",
    authorImg: "https://i.pravatar.cc/150?img=8",
    authorName: "Ali Haider",
  },
  {
    date: "30 May 2023",
    title: "Team Collaboration Tools",
    desc: "Invite team members and assign roles for better workflow.",
    image: "/images/blog/blog-3.png",
    authorImg: "https://i.pravatar.cc/150?img=9",
    authorName: "Zainab Sheikh",
  },
  {
    date: "06 Jun 2023",
    title: "CSV Export Enhancement",
    desc: "Export data with custom fields and advanced filtering options.",
    image: "/images/blog/blog-2.png",
    authorImg: "https://i.pravatar.cc/150?img=10",
    authorName: "Imran Siddiqui",
  },
  {
    date: "13 Jun 2023",
    title: "Two-Factor Authentication",
    desc: "Enhanced security with 2FA and biometric login options.",
    image: "/images/blog/blog-4.png",
    authorImg: "https://i.pravatar.cc/150?img=11",
    authorName: "Mariam Tariq",
  },
  {
    date: "20 Jun 2023",
    title: "Webhook Integration Support",
    desc: "Connect with your favorite tools using our webhook system.",
    image: "/images/blog/blog-6.png",
    authorImg: "https://i.pravatar.cc/150?img=12",
    authorName: "Kamran Ashraf",
  },
  {
    date: "27 Jun 2023",
    title: "Custom Domain Support",
    desc: "Use your own domain for emails and tracking links.",
    image: "/images/blog/blog-1.png",
    authorImg: "https://i.pravatar.cc/150?img=13",
    authorName: "Hira Jamil",
  },
  {
    date: "04 Jul 2023",
    title: "A/B Testing Feature",
    desc: "Test multiple variations to optimize your campaign performance.",
    image: "/images/blog/blog-5.png",
    authorImg: "https://i.pravatar.cc/150?img=14",
    authorName: "Faisal Mahmood",
  },
  {
    date: "11 Jul 2023",
    title: "Automated Reporting System",
    desc: "Schedule and receive automated reports directly in your inbox.",
    image: "/images/blog/blog-3.png",
    authorImg: "https://i.pravatar.cc/150?img=15",
    authorName: "Nida Abbas",
  },
  {
    date: "18 Jul 2023",
    title: "Smart Segmentation Tool",
    desc: "Segment your audience using AI-powered recommendations.",
    image: "/images/blog/blog-2.png",
    authorImg: "https://i.pravatar.cc/150?img=16",
    authorName: "Saad Iqbal",
  },
  {
    date: "25 Jul 2023",
    title: "Email Personalization Engine",
    desc: "Create hyper-personalized emails with dynamic content blocks.",
    image: "/images/blog/blog-4.png",
    authorImg: "https://i.pravatar.cc/150?img=17",
    authorName: "Amber Yousaf",
  },
  {
    date: "01 Aug 2023",
    title: "Template Builder Update",
    desc: "Drag-and-drop builder with 100+ new components and blocks.",
    image: "/images/blog/blog-6.png",
    authorImg: "https://i.pravatar.cc/150?img=18",
    authorName: "Waseem Akram",
  },
  {
    date: "08 Aug 2023",
    title: "Real-Time Notifications",
    desc: "Get instant alerts for important campaign events and milestones.",
    image: "/images/blog/blog-1.png",
    authorImg: "https://i.pravatar.cc/150?img=19",
    authorName: "Rabia Nasir",
  },
  {
    date: "15 Aug 2023",
    title: "Contact Management Overhaul",
    desc: "Improved contact organization with tags, lists, and folders.",
    image: "/images/blog/blog-5.png",
    authorImg: "https://i.pravatar.cc/150?img=20",
    authorName: "Talha Butt",
  },
  {
    date: "22 Aug 2023",
    title: "Spam Score Checker",
    desc: "Test your emails before sending to ensure deliverability.",
    image: "/images/blog/blog-3.png",
    authorImg: "https://i.pravatar.cc/150?img=21",
    authorName: "Sana Riaz",
  },
  {
    date: "29 Aug 2023",
    title: "Campaign Scheduler Enhancement",
    desc: "Schedule campaigns across multiple time zones effortlessly.",
    image: "/images/blog/blog-2.png",
    authorImg: "https://i.pravatar.cc/150?img=22",
    authorName: "Junaid Shah",
  },
 
];
