// File: app/blog/latestBlog/LatestData.ts
export const latestBlogData = [
  {
    id: 1,
    title: "Resend raises $3M",
    image: "/images/blog/blog-1.png",
    authorInfo: "Emily Carter - Feb 1, 2023",
    authorImage: "https://i.pravatar.cc/150?img=2",
  },
  {
    id: 2,
    title: "Scaling email delivery with edge infrastructure",
    image: "/images/blog/blog-2.png",
    authorInfo: "John Doe - Mar 12, 2023",
    authorImage: "https://i.pravatar.cc/150?img=3",
  },
  {
    id: 3,
    title: "Introducing transactional templates",
    image: "/images/blog/blog-3.png",
    authorInfo: "Sophia Patel - Apr 5, 2023",
    authorImage: "https://i.pravatar.cc/150?img=4",
  },
  {
    id: 4,
    title: "Why developers love Resend APIs",
    image: "/images/blog/blog-4.png",
    authorInfo: "Michael Lee - May 8, 2023",
    authorImage: "https://i.pravatar.cc/150?img=5",
  },
  {
    id: 5,
    title: "How we improved email rendering speed by 50%",
    image: "/images/blog/blog-5.png",
    authorInfo: "Isabella Gomez - Jun 14, 2023",
    authorImage: "https://i.pravatar.cc/150?img=6",
  },
  {
    id: 6,
    title: "Designing the perfect transactional email",
    image: "/images/blog/blog-6.png",
    authorInfo: "Daniel Kim - Jul 21, 2023",
    authorImage: "https://i.pravatar.cc/150?img=7",
  },
  {
    id: 7,
    title: "The future of developer-first email",
    image: "/images/blog/blog-7.png",
    authorInfo: "Ava Johnson - Aug 2, 2023",
    authorImage: "https://i.pravatar.cc/150?img=8",
  },
  {
    id: 8,
    title: "Our journey to SOC 2 compliance",
    image: "/images/blog/blog-8.png",
    authorInfo: "Ethan Brown - Sep 11, 2023",
    authorImage: "https://i.pravatar.cc/150?img=9",
  },
  {
    id: 9,
    title: "Building resilient infrastructure for scale",
    image: "/images/blog/blog-9.png",
    authorInfo: "Olivia Smith - Oct 3, 2023",
    authorImage: "https://i.pravatar.cc/150?img=10",
  },
  {
    id: 10,
    title: "Resend joins YC W23 batch",
    image: "/images/blog/blog-10.png",
    authorInfo: "Liam Anderson - Nov 15, 2023",
    authorImage: "https://i.pravatar.cc/150?img=11",
  },
  {
    id: 11,
    title: "Optimizing Node.js apps for better email throughput",
    image: "/images/blog/blog-11.png",
    authorInfo: "Mia Clark - Dec 4, 2023",
    authorImage: "https://i.pravatar.cc/150?img=12",
  },
  {
    id: 12,
    title: "How to track email engagement effectively",
    image: "/images/blog/blog-12.png",
    authorInfo: "Noah Wilson - Jan 10, 2024",
    authorImage: "https://i.pravatar.cc/150?img=13",
  },
  {
    id: 13,
    title: "Real-time analytics in email delivery",
    image: "/images/blog/blog-13.png",
    authorInfo: "Sophia Turner - Feb 2, 2024",
    authorImage: "https://i.pravatar.cc/150?img=14",
  },
  {
    id: 14,
    title: "Improving developer onboarding experience",
    image: "/images/blog/blog-14.png",
    authorInfo: "James Martinez - Feb 18, 2024",
    authorImage: "https://i.pravatar.cc/150?img=15",
  },
  {
    id: 15,
    title: "Why startups should prioritize deliverability",
    image: "/images/blog/blog-15.png",
    authorInfo: "Ella Robinson - Mar 12, 2024",
    authorImage: "https://i.pravatar.cc/150?img=16",
  },
  {
    id: 16,
    title: "Resend API v2 — new features and upgrades",
    image: "/images/blog/blog-16.png",
    authorInfo: "Lucas White - Apr 9, 2024",
    authorImage: "https://i.pravatar.cc/150?img=17",
  },
  {
    id: 17,
    title: "Behind the scenes: scaling to 10M emails/day",
    image: "/images/blog/blog-17.png",
    authorInfo: "Charlotte Hill - May 1, 2024",
    authorImage: "https://i.pravatar.cc/150?img=18",
  },
  {
    id: 18,
    title: "How AI helps us detect email delivery issues",
    image: "/images/blog/blog-18.png",
    authorInfo: "Henry Nguyen - May 22, 2024",
    authorImage: "https://i.pravatar.cc/150?img=19",
  },
  {
    id: 19,
    title: "Meet our new Resend dashboard",
    image: "/images/blog/blog-19.png",
    authorInfo: "Aria Baker - Jun 4, 2024",
    authorImage: "https://i.pravatar.cc/150?img=20",
  },
  {
    id: 20,
    title: "Top 5 email testing tools in 2024",
    image: "/images/blog/blog-20.png",
    authorInfo: "Jacob Harris - Jun 19, 2024",
    authorImage: "https://i.pravatar.cc/150?img=21",
  },
  {
    id: 21,
    title: "Improving bounce handling reliability",
    image: "/images/blog/blog-21.png",
    authorInfo: "Lily Walker - Jul 1, 2024",
    authorImage: "https://i.pravatar.cc/150?img=22",
  },
  {
    id: 22,
    title: "The tech stack powering Resend",
    image: "/images/blog/blog-22.png",
    authorInfo: "Mason Rivera - Jul 23, 2024",
    authorImage: "https://i.pravatar.cc/150?img=23",
  },
  {
    id: 23,
    title: "Handling millions of API requests per minute",
    image: "/images/blog/blog-23.png",
    authorInfo: "Grace Murphy - Aug 3, 2024",
    authorImage: "https://i.pravatar.cc/150?img=24",
  },
  {
    id: 24,
    title: "Deliverability best practices for 2025",
    image: "/images/blog/blog-24.png",
    authorInfo: "Logan Scott - Aug 26, 2024",
    authorImage: "https://i.pravatar.cc/150?img=25",
  },
  {
    id: 25,
    title: "How we built our custom email rendering engine",
    image: "/images/blog/blog-25.png",
    authorInfo: "Zoey Adams - Sep 7, 2024",
    authorImage: "https://i.pravatar.cc/150?img=26",
  },
  {
    id: 26,
    title: "Email authentication in the modern web",
    image: "/images/blog/blog-26.png",
    authorInfo: "William Thompson - Sep 24, 2024",
    authorImage: "https://i.pravatar.cc/150?img=27",
  },
  {
    id: 27,
    title: "Resend + Next.js integration guide",
    image: "/images/blog/blog-27.png",
    authorInfo: "Scarlett Lewis - Oct 5, 2024",
    authorImage: "https://i.pravatar.cc/150?img=28",
  },
  {
    id: 28,
    title: "Serverless email sending with Vercel",
    image: "/images/blog/blog-28.png",
    authorInfo: "Benjamin Evans - Oct 20, 2024",
    authorImage: "https://i.pravatar.cc/150?img=29",
  },
  {
    id: 29,
    title: "Improving reliability through distributed queues",
    image: "/images/blog/blog-29.png",
    authorInfo: "Hannah Mitchell - Nov 8, 2024",
    authorImage: "https://i.pravatar.cc/150?img=30",
  },
  {
    id: 30,
    title: "What’s next for Resend in 2025",
    image: "/images/blog/blog-30.png",
    authorInfo: "Jack Collins - Dec 15, 2024",
    authorImage: "https://i.pravatar.cc/150?img=31",
  },
];
