// File: components/EmailFeatures/FeatturesList.ts


export const emailFeatures = [
  {
    icon: "/images/Home/EmailFeatureSection/icon-1.png",
    title: "Proactive blocklist tracking",
    description:
      "Be the first to know if your domain is added to a DNSBLs such as those offered by Spamhaus with removal requests generated by Resend.",
  },
  {
    icon: "/images/Home/EmailFeatureSection/icon-2.png",
    title: "Faster Time to Inbox",
    description:
      "Send emails from the region closest to your users. Reduce delivery latency with North American, South American, and European regions.",
  },
  {
    icon: "/images/Home/EmailFeatureSection/icon-3.png",
    title: "Build confidence with BIMI",
    description:
      "Showcase your logo and company branding with BIMI. Receive guidance to obtain a VMC - the email equivalent of a checkmark on social media.",
  },
  {
    icon: "/images/Home/EmailFeatureSection/icon-4.png",
    title: "Managed Dedicated IPs",
    description:
      "Get a fully managed dedicated IP that automatically warms up and autoscales based on your sending volume, no waiting period.",
  },
  {
    icon: "/images/Home/EmailFeatureSection/icon-5.png",
    title: "Dynamic suppression list",
    description:
      "Prevent repeated sending to recipients who no longer want your email and comply with standards like the CAN-SPAM Act and others.",
  },
  {
    icon: "/images/Home/EmailFeatureSection/icon-6.png",
    title: "IP and domain monitoring",
    description:
      "Monitor your DNS configuration for any errors or regressions. Be notified of any changes that could hinder your deliverability.",
  },
];