// File: app/changelog/changelogsData.ts
export const changelogsData = [
  {
    date: "23 Mar 2023",
    title: "Update Click/Open Tracking via API",
    desc: "Manage the entire lifecycle of your domains programmatically.",
    image: "/images/changelog/cl-1.png",
    authorImg: "https://i.pravatar.cc/150?img=1",
    authorName: "Ahmad Hassan",
  },
  {
    date: "31 Mar 2023",
    title: "Improved Dashboard Performance",
    desc: "Enhanced analytics speed and optimized queries for faster insights.",
    image: "/images/changelog/cl-2.png",
    authorImg: "https://i.pravatar.cc/150?img=2",
    authorName: "Bilal Khan",
  },
  {
    date: "08 Apr 2023",
    title: "New Email Templates Library",
    desc: "Access 50+ professionally designed email templates for campaigns.",
    image: "/images/changelog/cl-3.png",
    authorImg: "https://i.pravatar.cc/150?img=3",
    authorName: "Sara Ahmed",
  },
  {
    date: "15 Apr 2023",
    title: "Multi-Language Support Added",
    desc: "Platform now supports 20+ languages for global reach.",
    image: "/images/changelog/cl-4.png",
    authorImg: "https://i.pravatar.cc/150?img=4",
    authorName: "Usman Ali",
  },
  {
    date: "22 Apr 2023",
    title: "Advanced Analytics Dashboard",
    desc: "Get deeper insights with our new analytics and reporting tools.",
    image: "/images/changelog/cl-5.png",
    authorImg: "https://i.pravatar.cc/150?img=5",
    authorName: "Ayesha Malik",
  },
  {
    date: "30 Apr 2023",
    title: "Dark Mode Implementation",
    desc: "Reduce eye strain with our sleek new dark mode interface.",
    image: "/images/changelog/cl-6.png",
    authorImg: "https://i.pravatar.cc/150?img=6",
    authorName: "Hassan Raza",
  },
  {
    date: "07 May 2023",
    title: "API Rate Limit Increase",
    desc: "Premium users now get 3x higher API rate limits.",
    image: "/images/changelog/cl-7.png",
    authorImg: "https://i.pravatar.cc/150?img=7",
    authorName: "Fatima Noor",
  },
  {
    date: "14 May 2023",
    title: "Mobile App Launch",
    desc: "Manage your campaigns on the go with our native mobile apps.",
    image: "/images/changelog/cl-8.png",
    authorImg: "https://i.pravatar.cc/150?img=8",
    authorName: "Ali Haider",
  },
  {
    date: "21 May 2023",
    title: "Team Collaboration Tools",
    desc: "Invite team members and assign roles for better workflow.",
    image: "/images/changelog/cl-9.png",
    authorImg: "https://i.pravatar.cc/150?img=9",
    authorName: "Zainab Sheikh",
  },
  {
    date: "28 May 2023",
    title: "CSV Export Enhancement",
    desc: "Export data with custom fields and advanced filtering options.",
    image: "/images/changelog/cl-10.png",
    authorImg: "https://i.pravatar.cc/150?img=10",
    authorName: "Imran Siddiqui",
  },
  {
    date: "05 Jun 2023",
    title: "Two-Factor Authentication",
    desc: "Enhanced security with 2FA and biometric login options.",
    image: "/images/changelog/cl-11.png",
    authorImg: "https://i.pravatar.cc/150?img=11",
    authorName: "Mariam Tariq",
  },
  {
    date: "12 Jun 2023",
    title: "Webhook Integration Support",
    desc: "Connect with your favorite tools using our webhook system.",
    image: "/images/changelog/cl-12.png",
    authorImg: "https://i.pravatar.cc/150?img=12",
    authorName: "Kamran Ashraf",
  },
  {
    date: "19 Jun 2023",
    title: "Custom Domain Support",
    desc: "Use your own domain for emails and tracking links.",
    image: "/images/changelog/cl-13.png",
    authorImg: "https://i.pravatar.cc/150?img=13",
    authorName: "Hira Jamil",
  },
  {
    date: "26 Jun 2023",
    title: "A/B Testing Feature",
    desc: "Test multiple variations to optimize your campaign performance.",
    image: "/images/changelog/cl-14.png",
    authorImg: "https://i.pravatar.cc/150?img=14",
    authorName: "Faisal Mahmood",
  },
  {
    date: "03 Jul 2023",
    title: "Automated Reporting System",
    desc: "Schedule and receive automated reports directly in your inbox.",
    image: "/images/changelog/cl-15.png",
    authorImg: "https://i.pravatar.cc/150?img=15",
    authorName: "Nida Abbas",
  },
  {
    date: "10 Jul 2023",
    title: "Smart Segmentation Tool",
    desc: "Segment your audience using AI-powered recommendations.",
    image: "/images/changelog/cl-16.png",
    authorImg: "https://i.pravatar.cc/150?img=16",
    authorName: "Saad Iqbal",
  },
  {
    date: "18 Jul 2023",
    title: "Email Personalization Engine",
    desc: "Create hyper-personalized emails with dynamic content blocks.",
    image: "/images/changelog/cl-17.png",
    authorImg: "https://i.pravatar.cc/150?img=17",
    authorName: "Amber Yousaf",
  },
  {
    date: "25 Jul 2023",
    title: "Template Builder Update",
    desc: "Drag-and-drop builder with 100+ new components and blocks.",
    image: "/images/changelog/cl-18.png",
    authorImg: "https://i.pravatar.cc/150?img=18",
    authorName: "Waseem Akram",
  },
];
